### ISSUE TITLE
Error when attempting to send graph

### ISSUE THREAD

**Issue by wingZero21** [sepulworld/tfsoa#30]
Hi,

When attempting to run the example to send the graph this does not seem to work. Getting the below error.

Details:
```
NoMethodError: undefined method `state_details' for nil:NilClass
	/root/tfsoa/lib/tfsoa.rb:155:in `block in <class:TerraformSOA>'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/builder.rb:138:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/urlmap.rb:65:in `block in call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/urlmap.rb:50:in `each'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/urlmap.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/lint.rb:49:in `_call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/lint.rb:37:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/showexceptions.rb:24:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/chunked.rb:43:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
	/usr/local/rvm/gems/ruby-2.2.2/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	/usr/local/rvm/gems/ruby-2.2.2/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	/usr/local/rvm/gems/ruby-2.2.2/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/handler/thin.rb:16:in `run'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/server.rb:264:in `start'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/lib/rack/server.rb:141:in `start'
	/usr/local/rvm/gems/ruby-2.2.2/gems/rack-1.5.5/bin/rackup:4:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.2.2/bin/rackup:23:in `load'
	/usr/local/rvm/gems/ruby-2.2.2/bin/rackup:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>```

**Comment by sepulworld** [comment]
Hi, are you adding the graph to an existing state? That is a requirement for this to work.

**Comment by wingZero21** [comment]
Hey,

Yeah apologies I have retried this now and the command runs, however when clicking on graph it mentions this.

```
Entity not found: /teamtest-tftest-terraformservice-live-3.png
```

**Comment by sepulworld** [comment]
No worries. You also need to have graphiz installed on the system running tfsoa. We leverage graphiz the generate the png file on the fly. Can you double check that it is installed? I need to add this to the docs.

**Comment by wingZero21** [comment]
Hey,

Yep that fixed the issue. The graphs work fine now.

Probably worth adding some required deps to the readme for installation for anyone else that might have the problem in the future.

Cheers!

**Comment by sepulworld** [comment]
Added to the docs: https://github.com/sepulworld/tfsoa/commit/38a57fc56604389862b6c36784dd69f5dc349b46
